// gendoc 由 cobra 命令树生成 doc/11-命令参考.md。
//
// 命令与标志一律不手写：这份文档是 --help 的产品化版本，手写必然漂移。
// 重新生成：go run ./hack/gendoc；CI 会重新生成并 git diff --exit-code。
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
	"github.com/structure-projects/somcli/cmd"
)

func main() {
	root := cmd.NewRootCommand()

	out, err := os.Create(filepath.Join("doc", "11-命令参考.md"))
	if err != nil {
		fatal(err)
	}
	defer out.Close()

	fmt.Fprintln(out, "<!-- 本文件由 hack/gendoc 自动生成，请勿手改。改命令/标志请改 cmd/ 后重新 go run ./hack/gendoc -->")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "# 命令参考")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "按命令树排列。每条命令的用法、标志、子命令与 `somcli <命令> --help` 完全一致。")
	fmt.Fprintln(out)

	// 关掉每条命令末尾的 "Auto generated by spf13/cobra on <date>"：
	// 带日期会让每次重新生成都产生 diff，CI 的 git diff --exit-code 永远红。
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		c.DisableAutoGenTag = true
		for _, child := range c.Commands() {
			walk(child)
		}
	}
	walk(root)

	// 广度优先：根命令在前，逐层向下，读起来与 help 的 Available Commands 同序。
	queue := []*cobra.Command{root}
	for len(queue) > 0 {
		c := queue[0]
		queue = queue[1:]

		var buf bytes.Buffer
		if err := doc.GenMarkdownCustom(c, &buf, linkHandler); err != nil {
			fatal(err)
		}
		// 去掉 cobra 写的 H2（根命令用文档标题即可，子命令用 ### 让层级更平）。
		body := stripH2(buf.String())
		if c.HasParent() {
			depth := strings.Count(c.CommandPath(), " ")
			fmt.Fprintf(out, "%s %s\n\n", strings.Repeat("#", depth+2), c.CommandPath())
			fmt.Fprintln(out, strings.TrimSpace(body))
		} else {
			fmt.Fprintln(out, strings.TrimSpace(body))
		}
		fmt.Fprintln(out)

		children := c.Commands()
		sort.Sort(byName(children))
		for _, child := range children {
			if child.IsAvailableCommand() && !child.IsAdditionalHelpTopicCommand() {
				queue = append(queue, child)
			}
		}
	}
}

// linkHandler 把 cobra 默认的 `somcli_install.md` 跨文件链接改成同文件锚点 `#somcli-install`，
// 因为所有命令都生成在同一份文档里。
func linkHandler(name string) string {
	base := strings.TrimSuffix(name, ".md")
	return "#" + strings.ReplaceAll(base, "_", "-")
}

// stripH2 去掉 GenMarkdownCustom 写的 `## <command path>` 首行，标题由我们自己控制层级。
func stripH2(s string) string {
	if i := strings.Index(s, "\n"); i >= 0 && strings.HasPrefix(s, "## ") {
		return s[i+1:]
	}
	return s
}

type byName []*cobra.Command

func (a byName) Len() int           { return len(a) }
func (a byName) Less(i, j int) bool { return a[i].Name() < a[j].Name() }
func (a byName) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "gendoc:", err)
	os.Exit(1)
}
