/*
Copyright 2023 Structure Projects

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package installer

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/structure-projects/somcli/pkg/types"
	"github.com/structure-projects/somcli/pkg/utils"
)

// installContainer 实现 method: container —— 拉镜像，并在 InstallDir 放一个同名包装脚本。
//
// 只拉镜像是不够的：用户写 method: container 装 helm，期望的是之后能直接敲 `helm`。
// 包装脚本自己探测 docker / podman，所以 somcli 不需要在 Go 侧判断运行时 ——
// 也就不会有"操作机装的是 docker、目标节点装的是 podman"这种判断错位。
func installContainer(res types.Resource) error {
	image, err := utils.ParseStr(res.Image, res)
	if err != nil {
		return fmt.Errorf("image 模板解析失败 (%s): %w", res.Image, err)
	}
	if image == "" {
		return fmt.Errorf("method: container 需要 image: 指明镜像")
	}
	// 镜像名要被嵌进生成的脚本，带换行就能把脚本改成任意内容
	if strings.ContainsAny(image, "\n\r") {
		return fmt.Errorf("image 不能包含换行: %q", image)
	}
	if res.Name == "" {
		return fmt.Errorf("method: container 需要 name: 作为命令名")
	}

	dir := utils.InstallDir(res)
	wrapper := filepath.Join(dir, res.Name)

	// 包装脚本内容。用带引号的 heredoc（<<'EOF'）写入，内容不经 shell 展开，
	// 里面的 "$@" 才能原样留给运行时而不是在生成时就被替换掉。
	script := strings.Join([]string{
		"#!/bin/sh",
		"# generated by somcli: method: container",
		"for rt in docker podman; do",
		"  command -v \"$rt\" >/dev/null 2>&1 && exec \"$rt\" run --rm -i " + image + " \"$@\"",
		"done",
		"echo 'no container runtime found (docker / podman)' >&2",
		"exit 1",
	}, "\n")

	cmds := []string{
		containerPullCmd(image),
		fmt.Sprintf("mkdir -p %s", shellQuote(dir)),
		fmt.Sprintf("cat > %s <<'SOMCLI_WRAPPER_EOF'\n%s\nSOMCLI_WRAPPER_EOF", shellQuote(wrapper), script),
		fmt.Sprintf("chmod 0755 %s", shellQuote(wrapper)),
	}

	return runMethodScripts(res, cmds)
}

func containerPullCmd(image string) string {
	return fmt.Sprintf(
		"if command -v docker >/dev/null 2>&1; then docker pull %s; "+
			"elif command -v podman >/dev/null 2>&1; then podman pull %s; "+
			"else echo '未找到容器运行时（docker / podman）' >&2; exit 1; fi",
		shellQuote(image), shellQuote(image))
}
