nodes:
  - host: "master"
    ip: "172.20.10.11"
    role: "master"
    user: "root"
    sshKey: "~/.ssh/id_rsa"
  - host: "node1"
    ip: "172.20.10.23"
    role: "worker"
    user: "root"
    sshKey: "~/.ssh/id_rsa"
  - host: "node2"
    ip: "172.20.10.24"
    role: "worker"
    user: "root"
    sshKey: "~/.ssh/id_rsa"
