
offline: true
debug: true
github_proxy: https://gh-proxy.com/
resources:
  - name: "docker-install"
    version: "2.4"
    urls:
      - "https://structured.oss-cn-beijing.aliyuncs.com/docker/{{.Version}}/docker-manager.sh"
    target: "{{.Workdir}}/scripts/{{.Filename}}"
    # checksum: "sha256:abc123..." # 注释则不开启验证
  - name: "docker"
    version: "24.0.6"
    method: "binary"
    urls:
      - "https://download.docker.com/linux/static/stable/x86_64/docker-{{.Version}}.tgz"
    target: "{{.Name}}-{{.Version}}.tgz"
    post_install:
      - "echo 执行安装脚本-携带参数"
    #checksum: "sha256:abc123..." # 注释则不开启验证
  - name: "docker-compose"
    version: "2.24.0" # 2.20.3
    method: "binary"
    urls:
      - "https://github.com/docker/compose/releases/download/v{{.Version}}/docker-compose-linux-x86_64"
    target: "{{.Name}}"
  - name: "cri-dockerd"
    version: "0.3.9"
    method: "binary"
    urls:
      - "https://github.com/Mirantis/cri-dockerd/releases/download/v{{.Version}}/cri-dockerd-{{.Version}}.amd64.tgz"
      - "https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.service"
      - "https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.socket"
    target: "{{.Filename}}"
    post_install:
      - "tar xvf cri-dockerd-{{.Version}}.amd64.tgz"
      - "sudo mv {{.CacheDir}}/cri-dockerd/cri-dockerd /usr/local/bin/"
      - "sudo mkdir -p /etc/systemd/system"
      - "sudo cp cri-docker.service /etc/systemd/system/"
      - "sudo cp cri-docker.socket /etc/systemd/system/"
      - "sudo systemctl daemon-reload"
      - "sudo systemctl enable cri-docker.service"
      - "sudo systemctl enable --now cri-docker.socket"
      - "sudo systemctl start cri-docker.service"
  - name: "k8s"
    version: "1.28.2"
    method: "binary"
    urls:
      - "https://storage.googleapis.com/kubernetes-release/release/v{{.Version}}/bin/linux/amd64/kubeadm"
      - "https://storage.googleapis.com/kubernetes-release/release/v{{.Version}}/bin/linux/amd64/kubectl"
      - "https://storage.googleapis.com/kubernetes-release/release/v{{.Version}}/bin/linux/amd64/kubelet"
    target: "{{.Filename}}"
    pre_install:
      - "echo k8s "
    post_install:
      - "cp {{.CacheDir}}/* /usr/local/bin"
      - "chmod +x /usr/local/bin/kubeadm"
      - "chmod +x /usr/local/bin/kubectl"
      - "chmod +x /usr/local/bin/kubelet"
    hosts:
      - "127.0.0.1"
    target: "{{.Filename}}"
  - name: "crictl"
    version: "1.28.0"
    urls:
      - "https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{.Version}}/crictl-v{{.Version}}-linux-amd64.tar.gz"
    target: "{{.Name}}"
    post_install:
      - "sudo tar zxvf {{.CacheDir}}/crictl-v{{.Version}}-linux-amd64.tar.gz -C /usr/local/bin"
      - "sudo chmod +x /usr/local/bin/crictl"
  # - name: "k8s-images"
  #   version: "1.28.0"
  #   urls:
  #     - "https://k8s-images.tar.gz"
  #   target: "{{.Name}}"
  #   post_install:
  #     - "echo 导入镜像"
nodes:
  - host: "tools"
    ip: "127.0.0.1"
    role: "manager"
    sshKey: "~/.ssh/id_rsa"
