cluster:
  type: "swarm"
  name: "my-swarm"
  nodes:
    - host: "swarm-mgr-01"
      ip: "192.168.1.100"
      role: "manager"
      sshKey: "~/.ssh/id_rsa"

  swarmConfig:
    advertiseAddr: "192.168.1.100" # 管理节点广播地址
    listenAddr: "0.0.0.0:2377" # 监听地址
    defaultAddrPool: # 地址池配置
      - "10.20.0.0/16"
    subnetSize: 24 # 子网大小
    dataPathPort: 4789 # 数据通道端口

###u7dfrdta
